const main = document.querySelector('#main');
const pages = {
  '/': home,
  '/platform': () => standardPage('The platform that brings cognitive signals into focus.', 'NEUROMORPH unifies assessment workflows, multimodal inputs, AI-assisted analysis and reporting into a clinician-centered cognitive assessment environment.', `One connected workflow|Move from assessment delivery to interpretable profile without a fragmented process.|A clearer cognitive picture|Bring memory, attention, language, executive function and visual-spatial signals together.|Designed for interpretation|Present domain-wise information and longitudinal context in a form that supports clinical conversation.`),
  '/assessment': assessment,
  '/ai-analysis': analysis,
  '/cognitive-profile': profile,
  '/clinical-value': clinical,
  '/validation': validation,
  '/about': about,
  '/contact': contact
};
function header(eyebrow, title, copy){return `<section class="page-hero"><div class="shell reveal"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${copy}</p></div></section>`}
function home(){return `<div class="shell"><section class="hero" id="hero-section"><video class="hero-video" autoplay muted loop playsinline preload="metadata" poster="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1920 1080'%3E%3Crect fill='%23070a0f' width='1920' height='1080'/%3E%3C/svg%3E"><source src="Videos/Video 1.mp4" type="video/mp4"></video><div class="hero-overlay"></div><div class="hero-gradient-overlay"></div><div class="hero-copy reveal"><div class="eyebrow">AI-powered cognitive assessment</div><h1>Understanding cognition.<br><em>Beyond a single test.</em></h1><p class="lead">NEUROMORPH brings together multimodal cognitive assessment, speech analysis, visual tasks, and longitudinal insights into one intelligent platform.</p><div class="hero-actions"><a class="button" href="#/platform">Explore the platform <span>â†—</span></a><a class="button button-ghost" href="#how-it-works">See how it works <span>â†“</span></a></div><p class="hero-note">CLINICAL DECISION SUPPORT Â· NOT A DIAGNOSTIC REPLACEMENT</p></div></section></div><section class="trust shell"><div><span>01 /</span>Multimodal assessment</div><div><span>02 /</span>AI-assisted analysis</div><div><span>03 /</span>Domain-wise profiling</div><div><span>04 /</span>Longitudinal insights</div><div><span>05 /</span>Clinician-centered reporting</div></section><section class="section"><div class="section-line"></div><div class="shell two-col"><div class="section-copy reveal"><div class="eyebrow">The challenge</div><h2>Traditional cognitive assessment captures moments. Cognition changes over time.</h2><p>Assessment information can be fragmented across tasks, observations, and visits. This makes patterns harder to see, compare, and communicate.</p><div class="problem-tags"><span class="tag">FRAGMENTED INPUTS</span><span class="tag">MANUAL INTERPRETATION</span><span class="tag">LIMITED CONTEXT</span><span class="tag">DIFFICULT COMPARISON</span></div></div><div class="fragment-map reveal"><i>Speech</i><i>Memory</i><i>Attention</i><i>Visual</i></div></div></section>${multimodal()}${productShowcase()}${cta()}`}
function dashboard(){return `<div class="profile-top"><b>ILLUSTRATIVE INTERFACE</b><span>ASSESSMENT / 03</span></div><div class="profile-grid"><div class="radar"></div><div class="bars">${[['Memory',72],['Attention',84],['Language',65],['Executive function',76],['Visual-spatial',80]].map(x=>`<div><div class="bar-label"><span>${x[0]}</span><span>${x[1]}</span></div><div class="bar-track"><i style="width:${x[1]}%"></i></div></div>`).join('')}<p class="micro">DEMONSTRATION VALUES ONLY</p></div></div>`}
function standardPage(title, copy, items){let cards=items.split('|');return `${header('NEUROMORPH PLATFORM',title,copy)}<section class="section"><div class="shell"><div class="feature-grid">${[0,2,4].map(i=>`<article class="feature-card reveal"><div class="icon">0${i/2+1}</div><h3>${cards[i]}</h3><p>${cards[i+1]}</p></article>`).join('')}</div></div></section>${cta()}`}
function assessment(){let data=[['Memory','Recall and recognition are explored through carefully designed, interactive activities.'],['Attention','Tasks can explore sustained focus and selective attention in context.'],['Language','Verbal fluency, word retrieval, and speech characteristics can contribute supplementary signals.'],['Executive function','Planning, flexibility, inhibition, and task switching can be represented in the assessment workflow.'],['Visual & spatial','Visual perception, spatial reasoning, and recall can be explored through abstract task experiences.']];return `${header('ASSESSMENT EXPERIENCE','Assessment designed around how cognition actually works.','A considered assessment experience brings together interaction, response, and context without implying that any one task is a medical diagnosis.')}<section class="section"><div class="shell"><div class="eyebrow">Assessment modalities</div><div class="assessment-list">${data.map((x,i)=>`<article class="assessment-card reveal"><small>MODULE 0${i+1}</small><h3>${x[0]}</h3><p>${x[1]}</p><div class="card-graphic"></div></article>`).join('')}<article class="assessment-card reveal"><small>SUPPLEMENTARY SIGNALS</small><h3>Speech analysis</h3><p>Speech-derived features such as rate, pause patterns, fluency, and response structure are analyzed within the broader assessment.</p><div class="card-graphic"></div></article></div></div></section>${cta()}`}
function analysis(){return `${header('AI ANALYSIS','From raw responses to meaningful cognitive signals.','NEUROMORPH uses AI-assisted processes to organize and analyze assessment information. Specific algorithms and outputs should be described transparently as the platform evolves.')}<section class="section"><div class="shell"><div class="eyebrow">The analysis pathway</div><h2>Information moves through a structured, interpretable flow.</h2><div class="pipeline reveal">${['Assessment data','Signal processing','Feature extraction','Multimodal analysis','Domain scoring','Cognitive profile'].map((x,i)=>`<span class="pipe">${x}</span>${i<5?'<b class="pipe-arrow">â†’</b>':''}`).join('')}</div><div class="placeholder">IMPLEMENTATION NOTE â€” This visual describes a conceptual workflow. Add verified technical methods, data handling details, and model documentation before representing them as product specifications.</div></div></section>${cta()}`}
function profile(){return `${header('COGNITIVE PROFILE','A cognitive profile built for a more complete conversation.','The cognitive profile brings domain-level insights and longitudinal context into an illustrative, clinician-centered interface.')}<section class="section"><div class="shell two-col"><div class="section-copy"><div class="eyebrow">Profile interface</div><h2>One assessment is a snapshot. Tracking reveals the trajectory.</h2><p>Repeated assessments can be compared over time to highlight stable, improving, or changing patterns that may benefit from professional review.</p><p class="micro">All interface values are synthetic and shown for demonstration only.</p></div><div class="profile-preview">${dashboard()}</div></div><div class="timeline reveal">${['Baseline','Follow-up 01','Follow-up 02','Follow-up 03','Comparison','Review','Conversation'].map(x=>`<div>${x.toUpperCase()}</div>`).join('')}</div></div></section>${cta()}`}
function clinical(){let people=[['For clinicians','Structured cognitive insights','Domain-wise visualization','Longitudinal comparison','Decision-support context'],['For caregivers','Clear reports','Understandable trends','Progress monitoring','Better clinical conversations'],['For researchers','Structured multimodal data','Repeatable workflows','Longitudinal analysis','Research integration potential'],['For individuals','Accessible screening experience','Understandable feedback','Personal cognitive profile','Professional follow-up where appropriate']];return `${header('CLINICAL VALUE','Designed to make cognitive information more understandable.','NEUROMORPH is intended to support structured assessment and monitoring for different people in the cognitive care ecosystem.')}<section class="section"><div class="shell"><div class="stakeholders">${people.map(x=>`<article class="stakeholder reveal"><div class="eyebrow">${x[0]}</div><h3>${x[1]}</h3><ul>${x.slice(2).map(y=>`<li>${y}</li>`).join('')}</ul></article>`).join('')}</div></div></section>${cta()}`}
function validation(){return `${header('VALIDATION','Scientific rigor needs transparent evidence.','NEUROMORPH\'s validation experience is designed to make supporting methods, context, and results clearâ€”without inventing metrics or overclaiming clinical performance.')}<section class="section"><div class="shell"><div class="eyebrow">Validation process</div><h2>A scientific process, made visible.</h2><div class="timeline reveal">${['Protocol','Participants','Assessment','Data collection','Analysis','Expert review','Results'].map(x=>`<div>${x.toUpperCase()}</div>`).join('')}</div><div class="feature-grid"><article class="feature-card"><div class="icon">01</div><h3>Clinical evaluation</h3><p>Document where and how the platform was evaluated, including the applicable protocol and context.</p></article><article class="feature-card"><div class="icon">02</div><h3>Expert feedback</h3><p>Include verified clinician or expert observations with clear attribution and scope.</p></article><article class="feature-card"><div class="icon">03</div><h3>Usability evaluation</h3><p>Present only measured findings, methodology, sample size, and relevant interpretation.</p></article></div><div class="placeholder">[ INSERT VERIFIED SAMPLE SIZE ] &nbsp; [ INSERT VERIFIED METHOD ] &nbsp; [ INSERT VERIFIED FINDING ]<br>Validation results must be based on the evaluation dataset and methodology described in accompanying clinical validation documentation.</div></div></section>${cta()}`}
function about(){let team=[['Vignesh.png','Vignesh Ram R','Lead Architect','Biomedical Engineering','Shapes the technical foundation of NEUROMORPH.'],['Ruben.png','Ruben Samuel S','Product Designer','Product / Technology','Translates complex workflows into a clear product experience.'],['Bhawana.png','Bhawana Jayachandran','AI Strategist','Artificial Intelligence','Guides responsible AI thinking across the platform.'],['Guna.png','Gunaseelan N','Market Strategist','Innovation / Business','Connects the product direction to real-world opportunity.'],['Hari.png','Harihara Sudhan R','Research Analyst','Research','Supports evidence-led thinking and structured research.']];return `${header('ABOUT NEUROMORPH','Technology for understanding cognition.','NEUROMORPH sits at the intersection of neuroscience, biomedical engineering, artificial intelligence, and human-centered design.')}<section class="section about-purpose"><div class="shell two-col"><div class="section-copy"><div class="eyebrow">Our purpose / vision</div><h2>Make cognitive information more connected, clear, and useful.</h2><p>We believe cognitive assessment should be thoughtful about both the science of measurement and the people who need to understand it. Our work focuses on building responsible technology that supports clinical and research conversations.</p></div><div class="purpose-note reveal"><span>OUR DIRECTION</span><strong>Connect the disciplines that help cognition become more understandable.</strong></div></div></section><section class="section team-section"><div class="shell"><div class="section-intro"><div><div class="eyebrow">Our team</div><h2>Built by a multidisciplinary team.</h2></div><p>NEUROMORPH brings together complementary perspectives across biomedical engineering, artificial intelligence, research, technology, and innovation.</p></div><div class="team-grid reveal">${team.map((x,i)=>`<article class="team-profile team-profile-${i+1}"><div class="team-photo"><img src="Pictures/${x[0]}" alt="${x[1]}" loading="lazy"><div class="team-contribution"><small>ROLE / CONTRIBUTION</small><span>${x[3]}</span></div></div><div class="team-meta"><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}</div></div></section>`}
function contact(){return `${header('CONTACT / DEMO','See cognition differently.','Explore how NEUROMORPH can support structured cognitive assessment and longitudinal insight.')}<section class="section"><div class="shell contact-layout"><div><div class="eyebrow">Talk to the team</div><h2>Let's build a clearer picture of cognition.</h2><p>For clinical collaboration, research collaboration, or technology partnership, get in touch. Please do not share sensitive personal health information in this form.</p><p class="micro">CLINICAL COLLABORATION<br>RESEARCH COLLABORATION<br>TECHNOLOGY PARTNERSHIP</p></div><form class="reveal" onsubmit="event.preventDefault();this.querySelector('button').textContent='REQUEST RECEIVED';"><div class="field"><label for="name">Name</label><input id="name" required /></div><div class="field"><label for="org">Organization</label><input id="org" /></div><div class="field"><label for="role">Role</label><input id="role" /></div><div class="field"><label for="email">Email</label><input id="email" type="email" required /></div><div class="field full"><label for="message">Message</label><textarea id="message"></textarea></div><p class="form-note">This demonstration form does not transmit data.</p><button class="button field full" type="submit">Request a demo <span>â†—</span></button></form></div></section>`}
function cta(){return `<section class="cta-band"><div class="shell reveal"><div class="eyebrow" style="justify-content:center">The next conversation</div><h2>Let's build a clearer picture of cognition.</h2><p>Explore NEUROMORPH and the future of multimodal cognitive assessment.</p><a class="button" href="#/contact">Request a demo <span>â†—</span></a></div></section>`}
function footer(){return `<div class="footer-grid"><div><a class="brand" href="#/"><span class="brand-mark">N</span><span>NEURO<span>MORPH</span></span></a><p>AI-powered multimodal cognitive assessment.</p></div><div><h4>Explore</h4><a href="#/platform">Platform</a><a href="#/assessment">Assessment</a><a href="#/ai-analysis">AI Analysis</a><a href="#/clinical-value">Clinical Value</a></div><div><h4>Company</h4><a href="#/validation">Validation</a><a href="#/about">About Us</a><a href="#/contact">Contact</a><a href="#/">Privacy & disclaimer</a></div></div><div class="footer-bottom"><span>Â© 2026 NEUROMORPH</span><span>TECHNOLOGY FOR UNDERSTANDING COGNITION.</span></div>`}
function render(){let route=location.hash.slice(1)||'/';main.innerHTML=(pages[route]||pages['/'])();document.querySelector('#footer').innerHTML=footer();document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+route));window.scrollTo(0,0);observe();document.querySelector('.nav')?.classList.remove('open');document.querySelector('.menu-toggle')?.setAttribute('aria-expanded','false')}
function observe(){let ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');ob.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>ob.observe(el))}
document.querySelector('.menu-toggle').addEventListener('click',e=>{let nav=document.querySelector('.nav'),open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});addEventListener('hashchange',render);addEventListener('scroll',()=>document.querySelector('.site-header').classList.toggle('scrolled',scrollY>8),{passive:true});render();

function workflow(){return `<div class="workflow-flow reveal"><div class="workflow-stage"><small>01 / INPUT</small><strong>Cognition</strong><span>Tasks, responses, speech</span></div><b>â†’</b><div class="workflow-stage"><small>02 / SIGNALS</small><strong>Signals</strong><span>Multiple observed inputs</span></div><b>â†’</b><div class="workflow-stage"><small>03 / ANALYSIS</small><strong>AI analysis</strong><span>Conceptual organization</span></div><b>â†’</b><div class="workflow-stage workflow-stage-final"><small>04 / OUTPUT</small><strong>Cognitive profile</strong><span>Context for review</span></div></div>`}
function productShowcase(){let screens=[['01','LOGIN','A considered entry point for the assessment workflow.'],['02','ASSESSMENT','Interactive tasks organized around cognitive domains.'],['03','SPEECH / ANALYSIS','Supplementary signals shown with transparent context.'],['04','COGNITIVE PROFILE','Domain performance and longitudinal review in one view.'],['05','REPORT','A structured output prepared for professional conversation.']];return `<section class="section product-section" id="how-it-works"><div class="shell"><div class="section-intro"><div><div class="eyebrow">Product experience</div><h2>See NEUROMORPH<br><em>in action.</em></h2></div><p>A product walkthrough, ready for verified interface captures. The frames below are intentionally placeholders so real screenshots can be added without changing the layout.</p></div><div class="product-rail reveal">${screens.map((x,i)=>`<article class="product-frame ${i===0?'is-active':''}"><div class="frame-top"><span>${x[0]} / ${x[1]}</span><i></i><i></i><i></i></div><div class="screen-placeholder"><span>SCREENSHOT ${x[0]}</span><b>${x[1]}</b><small>PLACEHOLDER FOR VERIFIED PRODUCT UI</small></div><p>${x[2]}</p></article>`).join('')}</div></div></section>`}
function multimodal(){let domains=['Memory','Attention','Language','Executive function','Visual-spatial','Speech'];return `<section class="section multimodal-section"><div class="shell"><div class="section-intro"><div><div class="eyebrow">Multimodal by design</div><h2>Multiple signals.<br><em>One cognitive profile.</em></h2></div><p>NEUROMORPH connects complementary assessment inputs so patterns can be viewed together, with the limits of each signal kept visible.</p></div><div class="domain-map reveal"><div class="domain-orbit orbit-left">${domains.slice(0,3).map((x,i)=>`<span style="--i:${i}">${x}</span>`).join('')}</div><div class="profile-core"><i></i><strong>COGNITIVE<br>PROFILE</strong><small>CONTEXTUAL VIEW</small></div><div class="domain-orbit orbit-right">${domains.slice(3).map((x,i)=>`<span style="--i:${i}">${x}</span>`).join('')}</div></div></div></section>`}

pages['/']=home;pages['/ai-analysis']=analysis;pages['/cognitive-profile']=profile;pages['/validation']=validation;

function originalAboutFn(){let team=[['Vignesh.png','Vignesh Ram R','Lead Architect','Shapes the technical foundation of NEUROMORPH.'],['Ruben.png','Ruben Samuel S','Product Designer','Translates complex workflows into a clear product experience.'],['Bhawana.png','Bhawana Jayachandran','AI Strategist','Guides responsible AI thinking across the platform.'],['Guna 2.png','Gunaseelan N','Market Strategist','Connects the product direction to real-world opportunity.'],['Hari.png','Harihara Sudhan R','Research Analyst','Supports evidence-led thinking and structured research.']];return `${header('ABOUT NEUROMORPH','Technology for understanding cognition.','NEUROMORPH sits at the intersection of neuroscience, biomedical engineering, artificial intelligence, and human-centered design.')}<section class="section about-purpose"><div class="shell two-col"><div class="section-copy"><div class="eyebrow">Our purpose / vision</div><h2>Make cognitive information more connected, clear, and useful.</h2><p>We believe cognitive assessment should be thoughtful about both the science of measurement and the people who need to understand it. Our work focuses on building responsible technology that supports clinical and research conversations.</p></div><div class="purpose-note reveal"><span>OUR DIRECTION</span><strong>Connect the disciplines that help cognition become more understandable.</strong></div></div></section><section class="section team-section"><div class="shell"><div class="section-intro"><div><div class="eyebrow">Our team</div><h2>Built by a multidisciplinary team.</h2></div><p>NEUROMORPH brings together complementary perspectives across biomedical engineering, artificial intelligence, research, technology, and innovation.</p></div><div class="team-grid reveal">${team.map((x,i)=>`<article class="team-profile team-profile-${i+1}"><div class="team-photo"><img src="Pictures/${x[0]}" alt="${x[1]}" loading="lazy"><div class="team-contribution"><small>ROLE / CONTRIBUTION</small><span>${x[3]}</span></div></div><div class="team-meta"><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}</div></div></section>${cta()}`}
pages['/about']=originalAboutFn;render();

// Handle hero video and prefers-reduced-motion
function setupHeroVideo(){
  const hero = document.getElementById('hero-section');
  const video = hero?.querySelector('.hero-video');
  
  if(!video) return;
  
  // Check for prefers-reduced-motion
  const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  
  if(prefersReducedMotion){
    video.pause();
    video.style.opacity = '0.4';
  } else {
    video.play().catch(err => {
      console.log('Autoplay prevented:', err);
    });
  }
  
  // Handle media query changes
  window.matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change', (e) => {
    if(e.matches){
      video.pause();
      video.style.opacity = '0.4';
    } else {
      video.play().catch(err => console.log('Playback error:', err));
      video.style.opacity = '0.6';
    }
  });
}

// Setup video on initial render
setupHeroVideo();

// Setup video on route changes
const originalRender = window.render;
window.render = function(){
  originalRender.call(this);
  setTimeout(setupHeroVideo, 100);
};
